.gitignore, README.md, poetry.lock, pyproject.toml, tests/robot_tests/home.robot, tests/robot_tests/resource.robot
RobotFramework installed and simple E2E test created 🤖
=> RobotFramework

.github/workflows/main.yml
TODO: 
- Lint etc. should be included
=> Initial github actions workflow

.github/workflows/main.yml
=> Workflow for Heroku deployment

README.md, docs/docs.md, src/static/css/main.css, src/static/src/style.css, src/static/tailwind.config.js, src/templates/index.html, src/templates/layout.html, src/templates/login.html, src/templates/test.html, src/templates/testdata.html, tasks.py
TailwindCSS added and wrote shortly about it to docs. Moved documentation to separate directory because README was getting quite long. 🤓
=> Tailwind CSS added to project & documentation folder created.

.github/workflows/main.yml, Dockerfile, src/app.py, src/config.py, tasks.py
Heroku now uses a docker! ✨ Changes include:
- Modification to Dockerfile. Added disable poetry virtualenvs since docker's convention is to not use virtualenvs, because containers themselves provide sufficient isolation. Read more [here](https://stackoverflow.com/questions/53835198/integrating-python-poetry-with-docker).
- Modification to actions workflow main.yml. Should now deploy using docker and moved heroku email address to repo secrets.
=> Modifications for Heroku docker deployment

src/app.py, src/templates/edit.html, src/templates/index.html, src/templates/new.html, src/tests/robot_tests/home.robot, src/tests/robot_tests/resource.robot
- Redirect logged out user when trying to access /edit or /new
- Removed unnecessary links from app (test html templates still exist but aren't linked to)
- Redirect to main page after Google login
- Extend layout to all existing pages
- Add clock skew allowance to Google SSO verification to fix Token used too early error
- Update tests accordingly
=> Minor app enhancements

.github/workflows/main.yml, run_robot_tests.sh, src/app.py
CI build workflow now runs Robot framework e2e tests. Closes #69
=> Add robot tests to CI workflow

src/app.py, src/static/css/main.css, src/static/src/style.css, src/templates/backdoor_login.html, src/templates/edit.html, src/templates/google_login.html, src/templates/index.html, src/templates/layout.html, src/templates/layout_login.html, src/templates/new.html, src/templates/test.html, src/templates/testdb.html, src/templates/testdb_new.html, src/tests/robot_tests/backdoor_login.robot, src/tests/robot_tests/home.robot
Tidied up the look of the app. Some E2E-tests were modified to work correctly with the changes to text and styles. 🤓
=> Unify the look of the application

src/templates/surveys.html, src/views.py
TODO: 
SQL-komennot tulisi varmaankin refaktoroida routes-luokasta omiin luokkiinsa toiminnallisuuden mukaan. Näin saataisiin yksikkötestauttua helpommin, single responsibility principleä kunnioittaen.
Toteutan metodin yksikkötestauksen kun meidän mock-tietokantamme on valmis.
=> Add /testdb/get_surveys route

src/db_queries.py, src/templates/view_survey.html, src/tests/robot_tests/home.robot, src/tests/robot_tests/resource.robot, src/views.py
Created simple e2e tests but tests should be expanded when working on functionality of adding questions
=> Questions relating to a survey can now be fetched from the database (#104)

src/db_queries.py, src/views.py
Removed the list of google accounts from the code. Changed the authorization to look into database instead of the fixed list.
=> change local login authorization from fixed list to local database

src/app.py, src/db_queries.py, src/templates/home/index.html, src/templates/layout.html, src/templates/surveys/edit.html, src/templates/surveys/statistics.html, src/templates/surveys/view_survey.html, src/tests/robot_tests/home.robot, src/views/home.py, src/views/surveys.py, src/views_obsolete.py
- Add links to view surveys on the list of surveys on main page
- Adjust top bar
- Add a button to open a form for editing a survey
- Add a button to open a statistics page for a survey
=> Add survey open, edit and statistics buttons

src/app.py, src/views/statistics.py
=> Add statistics page blueprint

src/tests/robot_tests/create_survey.robot
Check that a logged out user can't access the survey creation page
=> Add a robot test for survey creation

.coveragerc, .github/workflows/deploy_to_test.yml, pytest.ini, src/app.py, src/config.py
This took some trial and error... SurveyRepository tests are now working in the actions pipeline. What I did is:
- Added URI to Heroku Test Env DB to Repository secrets, passing it as environment variable to the app.
- Had some trouble because def load_config function required a the environment to be specified in an environment variable (we had forgotten to set it here in github). So the tests failed because the function def load_config was returning None
=> SurveyRepository tests now work in Actions pipeline

.github/workflows/deploy_to_prod.yml
Accidentally broke this automation. This should fix it.
=> Fix deploy_to_prod.yml

src/repositories/survey_repository.py, src/services/survey_service.py, src/templates/questions/edit_question.html, src/templates/questions/new_question.html, src/tests/repositories/survey_repository_test.py, src/tests/robot_tests/add_answer.robot, src/tests/robot_tests/add_question.robot, src/tests/robot_tests/home.robot, src/tests/robot_tests/resource_add_answer.robot, src/tests/services/survey_service_test.py, src/views/surveys.py
Enabled creating answers both when creating a new question and when editing an already existing one. Also enabled deleting answers while editing questions. These functionalities have also been unit and robot tested.
=> Dev creating answers

src/app.py, src/templates/layout.html, src/templates/logs/logs.html, src/tests/repositories/survey_repository_test.py, src/views/logs.py
Adds html-template, routing and link from home page
Closes #215, closes #216
=> Audit log frontend

src/tests/robot_tests/audit_log.robot, src/tests/robot_tests/delete_question.robot, src/tests/robot_tests/edit_category.robot, src/tests/robot_tests/event_log.robot, src/tests/robot_tests/resource.robot, src/tests/robot_tests/resource_login.robot, src/views/statistics.py, src/views/surveys.py
- Tests basic viewing of the log page
- Checked that view functions require logging in, closes #230
=> Robot tests for event log + login checks

.github/workflows/deploy_to_prod.yml
Added a command to initialize the test db.
=> Fix deploy_to_prod workflow

src/static/css/main.css, src/templates/components/macros/buttons.html, src/templates/components/sections/survey_deletition_modal.html, src/templates/components/sections/survey_header.html, src/templates/surveys/view_survey.html, src/tests/robot_tests/delete_edit_survey.robot, src/tests/robot_tests/resource_delete_edit_survey.robot, src/views/surveys.py
When deleting a survey, a modal is displayed where the user has to confirm the deletion. Dletion is confirmed by writing the name of the survey.
=> Deletion confirmation

src/tests/robot_tests/delete_question.robot, src/tests/robot_tests/home.robot, src/tests/robot_tests/resource_delete_question.robot
=> Fix delete_question e2e test

src/static/css/main.css, src/templates/home/list_admins.html, src/tests/robot_tests/admins.robot
- Styling changes to admin page
- Closes #245
=> Admin page styling unified with rest of the app

src/static/css/main.css
The updated `main.css` file, created automatically.
=> Tailwind updates

src/templates/layout.html, src/templates/layout_login.html, src/tests/robot_tests/edit_category.robot, src/views/home.py, src/views/logs.py, src/views/statistics.py, src/views/surveys.py
Added notifications logic to routes using Flasks flash(). The templates display the notifications as a basic text element. Did not do e2e-testing and leaving it for task #281.
Decided to break notifications to into three categories: **Errors**, **Warnings** and **Confirmations**.
- Deletion of surveys
- Creation of surveys
- Trying to delete category that has questions linked to it
- Inappropriate inputs (empty fields)
- Accessing pages when not logged in
=> Notifications logic to routes

src/repositories/survey_repository.py, src/tests/repositories/survey_repository_test.py, src/tests/services/survey_service_test.py
- A questions updatedAt field changes when an answer is created or deleted.
- The surveys updatedAt field is changed when a question or category is updated, created or deleted.
- survey_repository function get_question() returns also the relevant questions updatedAt value.
Unit testing with answer addition, removal and updating is incomplete; I have done local manual testing to verify proper function (and will proceed to do so in the test enviroment)
E2E tests could be considered, but I'm not sure if they are worthwhile as time based testing is rather complicated.
=> UpdatedAt values

src/services/survey_service.py, src/static/css/main.css, src/static/js/scripts.js, src/templates/components/sections/notification.html, src/templates/layout.html, src/templates/layout_login.html, src/templates/surveys/view_survey.html, src/tests/robot_tests/create_survey.robot, src/tests/robot_tests/delete_edit_survey.robot, src/tests/robot_tests/edit_category.robot, src/tests/robot_tests/home.robot, src/tests/robot_tests/resource.robot, src/views/surveys.py
Created a notification element to UI:
- Reflects category of notification by color and icon
- Can be dismissed by clicking X
- RobotTests check that notification is showed
=> Dismissable notification element to UI

src/tests/repositories/survey_repository_test.py, src/tests/services/survey_service_test.py
- If statements now visited while testing
- Survey repo unused test variables removed
- Closes #257
=> Added unit test for category update if statements

src/repositories/survey_repository.py, src/tests/repositories/survey_repository_test.py, src/views/home.py, src/views/logs.py, src/views/surveys.py
- Couple of database queries for generating the stats
- Pylint bits and bobs
=> Survey repository functions for answer distribution and number of submissions

src/static/css/main.css, src/templates/questions/edit_question.html, src/templates/surveys/edit_category.html, src/templates/surveys/statistics.html, src/tests/robot_tests/add_question.robot, src/tests/robot_tests/edit_category.robot, src/tests/robot_tests/edit_question.robot, src/views/statistics.py, src/views/surveys.py, tasks.py
- Back button on category page
- Back button on question page
- Pass survey path variable to category and question templates
- Closes #273 
- Removed duplicate login checks from survey views
- Some prep for stats page done
=> Links for return to survey page on question and category pages

src/templates/questions/edit_question.html, src/tests/robot_tests/edit_question.robot
Category_weights accepts a precision of 0.1. This can be changed in the edit_question.html `step` parameter.
=> Category weights accept floats

src/repositories/survey_repository.py, src/services/survey_service.py, src/templates/questions/edit_question.html, src/tests/repositories/survey_repository_test.py, src/tests/robot_tests/add_answer.robot, src/tests/robot_tests/resource_add_answer.robot, src/tests/services/survey_service_test.py, src/views/surveys.py
Enabled editing answers and deleted add answer option while incorporating it into save changes. Also fixed a few lint problems and updated and made robot and unit tests.
=> Dev editing answers

src/static/css/main.css, src/templates/components/macros/form_elements.html
Form labels truncate if text overflows. Closes #310
=> Form labels truncate if text overflows

src/repositories/survey_repository.py, src/services/survey_service.py, src/tests/repositories/survey_repository_test.py, src/tests/services/survey_service_test.py
Created a function for fetching a list of users who have submitted a given survey (by id of survey). Function created in both Survey Repository and Service.
Function returns a list of lists. Each containing:
[user_id, user_email, group_name_of_user, answer_time]
Closes #330
=> Fetch list of users who have submitted a given survey

src/static/css/main.css, src/templates/components/macros/statistics_elements.html, src/templates/components/sections/survey_categories.html, src/templates/surveys/statistics.html, src/tests/robot_tests/resource.robot, src/tests/robot_tests/statistics.robot, src/views/statistics.py
statistics.py ohjaa pois liikenteen tuotantoympäristössä.
Kategorialistaus uudessa templatessa; vaatinee vielä viilausta.
=> Add list categories in statistics view, stop access to statistics in production enviroment.

schema.sql, src/repositories/survey_repository.py, src/tests/repositories/survey_repository_test.py
- Database query can be filtered by user group
- Added some user answer data to the database for testing
=> Filter answer distribution by user group

src/repositories/survey_repository.py, src/services/survey_service.py, src/tests/repositories/survey_repository_test.py, src/tests/services/survey_service_test.py
- Edited SurveyRepository `get_users_who_answered_survey` to accept a timerange as parameters. If a timerange is given, the function queries the DB so that only users who answered a survey inside the given timerange are returned.
- Created new SurveyService function `get_users_who_answered_survey_in_timerange`. This function checks that the timerange is valid.
- Created tests for all this.
Closes #331
=> Filter users who answered a given survey by a timerange

src/repositories/survey_repository.py, src/services/survey_service.py, src/templates/surveys/statistics.html, src/tests/helper_test.py, src/tests/repositories/survey_repository_test.py, src/tests/robot_tests/statistics.robot, src/tests/services/survey_service_test.py, src/views/statistics.py
- First version: Only text field inputs for filter values
- Also fixed a minor bug in an unittest: test_plot_answer_dist_for_questions_creates_png_files
=> User filtering in statistics page

src/views/statistics.py
Removed the redirect from stastics page
=> Enable statistics page in prod

src/repositories/survey_repository.py, src/services/survey_service.py, src/tests/repositories/survey_repository_test.py, src/tests/robot_tests/edit_category.robot, src/tests/services/survey_service_test.py, src/views/statistics.py
Survey_service now calls  `create_placeholder_category_result(self, category_id)` method when creating a new category.
Also add: get_category_results function.
=> Initial category_results functions

src/templates/components/sections/survey_results.html, src/templates/surveys/edit_survey_results.html, src/templates/surveys/view_survey.html, src/views/surveys.py
- Added a module to the survey page for survey results and [a form for adding a survey result](https://test-superadmin3000.herokuapp.com/surveys/8/new-survey-result) with a cutoff of 1.0
- Not yet included: db operations, submitting the form, robot tests
=> Add form for adding (the first) survey result

src/repositories/survey_repository.py, src/services/survey_service.py, src/templates/surveys/statistics.html, src/tests/robot_tests/statistics.robot, src/tests/services/survey_service_test.py, src/views/statistics.py, src/views/surveys.py
- Addes filtering by email
- In statistics page, the list of users is shown only if the filter is used
=> Stats: Filter users by email

src/repositories/survey_repository.py, src/services/survey_service.py, src/tests/repositories/survey_repository_test.py, src/tests/services/survey_service_test.py
Calculate average scores now supports filtering by user group and timerange. 🤯
- Updated existing SurveyRepository function to support filtering
- Expanded SurveyRepository docstrings for function
- Updated SurveyService function to support filtering
- Updated tests accordingly
=> Calculate average scores by category from filtered data

src/static/css/main.css, src/templates/components/macros/category_results.html, src/templates/surveys/edit_category.html, src/tests/robot_tests/category_results.robot, src/views/surveys.py
Edit category page now lists available category results. Save & Delete buttons do not currently work.
=> Add listing of category results to edit category page

src/repositories/survey_repository.py, src/templates/components/macros/survey_elements.html, src/templates/components/sections/survey_header.html, src/templates/components/sections/survey_results.html, src/templates/surveys/edit_survey_results.html, src/tests/repositories/survey_repository_test.py, src/tests/robot_tests/resource_manage_results.robot, src/tests/robot_tests/survey_results.robot, src/views/surveys.py
Changed the Add result button to Manage results and updated the page for creating survey results to include existing results. For each result a delete button exists but is not yet working. I also added a link to the survey on the website the survey is answered on to the survey view.
=> Dev editing survey results

src/helper.py, src/templates/surveys/statistics.html, src/tests/helper_test.py, src/tests/robot_tests/statistics.robot, src/views/statistics.py
- Toggle filters now visible also when filtering by time only
- Toggle filters now visible also when filtering by email
- Closes #385
=> Missing toggle buttons added

src/repositories/survey_repository.py, src/services/survey_service.py, src/templates/components/macros/category_results.html, src/templates/surveys/edit_category.html, src/tests/repositories/survey_repository_test.py, src/tests/robot_tests/edit_category.robot, src/tests/robot_tests/resource_edit_category.robot, src/tests/services/survey_service_test.py, src/views/surveys.py
- Category result creation possible if the cutoff value is not already found for the category
- Automatically create result for cutoff value 1.0 when creating a category
- Closes #390
=> Creating category results now possible

src/static/css/main.css, src/static/js/scripts.js, src/templates/components/macros/form_elements.html, src/templates/components/macros/statistics_elements.html, src/templates/surveys/statistics.html, src/tests/robot_tests/statistics.robot, src/views/statistics.py
Did some UI work on the statistics page.
- Better use of space on screen 🪐
- DateTime input for filtering 🗓️
- Better tables 🤯
=> A revamped statistics view

src/repositories/survey_repository.py, src/services/survey_service.py, src/templates/components/macros/statistics_elements.html, src/templates/surveys/statistics.html, src/tests/helper_test.py, src/tests/repositories/survey_repository_test.py, src/tests/robot_tests/statistics.robot, src/tests/services/survey_service_test.py, src/views/statistics.py, src/views/surveys.py
=> Stats: Show both, filtered and full averages

src/repositories/survey_repository.py, src/services/survey_service.py, src/templates/components/macros/category_results.html, src/templates/questions/edit_question.html, src/templates/surveys/edit_category.html, src/tests/helper_test.py, src/tests/repositories/survey_repository_test.py, src/tests/robot_tests/category_results.robot, src/tests/robot_tests/edit_category.robot, src/tests/services/survey_service_test.py, src/views/surveys.py
=> Enables deleting category results

src/repositories/survey_repository.py, src/services/survey_service.py, src/tests/robot_tests/statistics.robot, src/tests/services/survey_service_test.py, src/views/statistics.py
=> Add email filtering support to averages

src/templates/surveys/edit_category.html, src/tests/robot_tests/edit_category.robot
=> Hide category result component when creating a new category

schema.sql, src/repositories/survey_repository.py, src/services/survey_service.py, src/tests/repositories/survey_repository_check_survey_status_test.py, src/tests/repositories/survey_repository_test.py, src/tests/services/survey_service_test.py
Closes #438.
`check_survey_status()` recieves a survey id and returns a list as follows:
```
[           
status :                        (str) 'red','yellow' or 'green',
no_survey_results :               (bool),
no_categories :                  (bool),
categories_without_results :    (list) [category names],
no_questions :                  (bool),
questions_without_answers :     (list) [question names],
questions_without_categories :  (list) [category names],
categories_without_questions :  (list) [category names]
]
```
=> Check survey status function

schema.sql, src/repositories/survey_repository.py, src/templates/surveys/statistics.html, src/tests/repositories/survey_repository_test.py, src/tests/robot_tests/statistics.robot, src/views/statistics.py
=> Include non-registered users in statistics

src/templates/components/macros/survey_elements.html, src/templates/questions/edit_question.html, src/templates/surveys/edit_category.html, src/templates/surveys/edit_survey_results.html, src/tests/robot_tests/add_answer.robot, src/tests/robot_tests/edit_category.robot, src/tests/robot_tests/survey_results.robot, src/views/surveys.py
Adds delete confirmations to the delete buttons which didn't have them.
closes #426
=> Add delete confirmations

src/templates/components/macros/survey_elements.html, src/templates/components/sections/survey_categories.html, src/templates/components/sections/survey_questions.html, src/templates/components/sections/survey_results.html, src/templates/surveys/edit_survey_results.html, src/tests/robot_tests/add_answer.robot, src/tests/robot_tests/create_survey.robot, src/tests/robot_tests/edit_category.robot, src/tests/robot_tests/edit_question.robot, src/tests/robot_tests/survey_results.robot, src/views/surveys.py
- Fallback for category results added if there are no results
- Realign the edit&delete buttons on the survey page
- Some other minor UI improvements
=> A couple of small fixes

schema.sql, src/helper.py, src/repositories/survey_repository.py, src/services/survey_service.py, src/templates/components/sections/survey_categories.html, src/tests/helper_test.py, src/tests/repositories/survey_repository_test.py, src/tests/robot_tests/edit_category.robot, src/tests/services/survey_service_test.py, src/views/surveys.py
- Display error message when deleting a category which is the only category weight for questions
- Remove category from category weights in questions when deleting
- Remove category results when deleting the category
- Closes #442
=> Fixed category deletion

src/repositories/survey_repository.py, src/services/survey_service.py, src/templates/components/macros/survey_elements.html, src/templates/home/index.html
- Closes #314 
- Changed from brackets to dot notation in survey_elements.html while I was at it
- Included in the docstrings a list of fields of the return objects of related functions both in backend and in html code
=> Remove survey id's from front page; minor code improvements

src/static/css/main.css, src/static/src/style.css, src/templates/components/sections/survey_header.html, src/templates/components/sections/survey_status.html, src/templates/components/sections/survey_status_modal.html, src/templates/surveys/view_survey.html, src/tests/robot_tests/resource.robot, src/tests/robot_tests/resource_survey_status.robot, src/tests/robot_tests/survey_status.robot, src/tests/robot_tests/utils.py, src/views/surveys.py
Survey page feature a tag displaying the status of the survey. Tag can be clicked to display modal with more information.
=> Status of survey on survey page

src/repositories/survey_repository.py
=> Fixes the calculation of filtered averages

src/static/css/main.css, src/templates/components/macros/basic_elements.html, src/templates/components/macros/survey_elements.html, src/templates/components/sections/notification.html, src/templates/components/sections/survey_categories.html, src/templates/components/sections/survey_header.html, src/templates/components/sections/survey_questions.html, src/templates/components/sections/survey_results.html, src/templates/home/index.html, src/templates/layout.html, src/templates/surveys/edit_category.html, src/templates/surveys/view_survey.html, src/tests/robot_tests/edit_category.robot, src/tests/robot_tests/home.robot
- Unification of spacing
- Added titles similar to other pages
- Pages navigation bar width matches width of main elements
- Survey cards show survey status using a colored stripe
Closes #267
=> Front end unification

src/helper.py, src/repositories/survey_repository.py, src/services/survey_service.py, src/templates/surveys/statistics.html, src/tests/robot_tests/statistics.robot, src/tests/services/survey_service_test.py, src/views/statistics.py
Backend now returns None if there are no applicable user submissions -> frontend shows no charts
Closes #462
=> Fix distribution charts behaving weird with no submissions

src/repositories/survey_repository.py, src/templates/components/sections/category_results.html, src/templates/components/sections/survey_status_modal.html, src/tests/repositories/survey_repository_check_survey_status_test.py, src/tests/robot_tests/edit_category.robot, src/views/surveys.py
- Closes #469 
- Closes #479 
- Closes #470
=> Category results deleted before deleting category

src/services/survey_service.py, src/templates/components/macros/survey_elements.html, src/templates/components/sections/survey_status.html, src/templates/components/sections/survey_status_modal.html, src/tests/services/survey_service_test.py
Modified SurveyService to return a dictionary in check_survey_status. Dictionary makes the code more readable.
=> SurveyService check_survey_status now returns a dictionary

.github/workflows/checks-for-docs.yml
No need to run the whole test pipeline when creating documentation, but getting the required checks would be nice when doing PRs 😸 
Created a separate workflow file as per the instructions here https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks
=> Create a separate workflow for doc files etc

Documentation/SurveyStatus.md
Created SurveyStatus.md in documentation. Closes #488
=> Documentation for survey status functionality

Documentation/User guide.md
Created user guide with survey creation workflow. Closes #491
[Preview of the document](https://github.com/Ronttikasa/SuperAdmin3000/blob/main/Documentation/User%20guide.md)
Document can be expanded with other functionalities of the app if needed
=> User guide for survey creation

src/repositories/survey_repository.py
Updated deleting questions to delete related question and user answers.
=> Dev deleting questions
